name: Run Xtream JSON and Upload to R2

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

  R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

  XTREAM_PRE_CACHE_URL: ${{ secrets.XTREAM_PRE_CACHE_URL }}
  XTREAM_CACHE_URL: ${{ secrets.XTREAM_CACHE_URL }}

  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}


jobs:
  run-xtream-json:
    runs-on: ubuntu-latest
 #   needs: run-xtream-m3u

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clone Private Py Repo
        run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/opitiopiti/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests boto3

      - name: Run Xtream Maker Final 
        run: python private_py/xtream/xtreammakingfinal.py

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Configure AWS for Cloudflare R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto

      - name: Upload JSON files to Cloudflare R2
        run: |
          aws s3 cp series_full_updated.json s3://iptv/full.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type application/json

          aws s3 live_premium_updated.json s3://iptv/premium.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type application/json

          aws s3 cp vod_premium_updated.json s3://iptv/standard.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type application/json
