name: Run Xtream JSON and Upload to R2

on:
  workflow_dispatch:

jobs:
  run-xtream-json:
    runs-on: ubuntu-latest
    needs: run-xtream-m3u

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clone Private Py Repo
        run: git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/opitiopiti/Py.git private_py

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests boto3

      - name: Run Xtream Full Script
        run: python private_py/xtream/jsonsistemi/convert_full.py

      - name: Run Xtream Premium Script
        run: python private_py/xtream/jsonsistemi/convert_premium.py

      - name: Run Xtream Standard Script
        run: python private_py/xtream/jsonsistemi/convert_standard.py

      - name: Commit times.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add xtream/times.json || true
          git diff --cached --quiet || git commit -m "times.json g√ºncellendi [auto]"
          git pull --rebase origin main || true
          git push origin main || true

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS for Cloudflare R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.region auto

      - name: Upload JSON files to Cloudflare R2
        run: |
          aws s3 cp xtreamjson/series_full.json s3://iptv/full.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type application/json

          aws s3 cp xtreamjson/live_premium.json s3://iptv/premium.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type application/json

          aws s3 cp xtreamjson/vod_premium.json s3://iptv/standard.json \
            --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --content-type application/json
